name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build APK with Docker (run as non-root)
      run: docker run --rm -u $(id -u):$(id -g) -v ${{ github.workspace }}:/workspace -w /workspace kivy/buildozer:latest buildozer android debug -- --assume-yes

    - name: Upload APK
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: SidikiToureSTEM-APK
        path: bin/*.apk
